# CMakeLists.txt for modules

# Add subdirectories for each module
add_subdirectory(capability_module)
add_subdirectory(chat)
add_subdirectory(logos_irc)
add_subdirectory(package_manager)
add_subdirectory(simple_module)
add_subdirectory(template_module)
add_subdirectory(waku_module)
add_subdirectory(wallet_module)
add_subdirectory(kvdb)
